### ISSUE TITLE
Thats good work

### ISSUE THREAD

**Issue by msizec** [farismalaeb/Powershell#6]
You've done a gret work for the community, thx a lot

**Comment by farismalaeb** [comment]
Thanks, @msizec, for the support. These things keep me motivated to do more.
But tell me, which script you liked the most :)

**Comment by msizec** [comment]
in fact I didn't see your others scripts. I was looking for a way to find ACL of entire ad objects for security reporting purpose and find your ADSecurityReporter module.

By the way, Ive changed it a bit (translation in french, conversion of SID (identityreference), utf8 csv encoding)
